name: 公司2定时巡检
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *'
jobs:
  run-task:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: 执行巡检
        env:
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID_COMP2: ${{ secrets.TG_CHAT_ID_COMP2 }}
        run: python comp2.py
