name: 大户账号巡检
on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"  # 每小时一次

jobs:
  check-apps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run check script
        env:
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID_DAHU }}
          # TG_CHAT_ID_COMP2: ${{ secrets.TG_CHAT_ID_COMP2 }}  # 第二个群
        run: python dahucheck.py
