name: TG个人账号定时推送广告
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 */4 * * *" # UTC时间，每4小时执行一次，降低封号风险

jobs:
  send-ad:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 配置Python3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: 安装依赖 Pyrogram
        run: pip install pyrogram

      - name: 执行发送脚本
        env:
          TG_API_ID: ${{ secrets.TG_API_ID }}
          TG_API_HASH: ${{ secrets.TG_API_HASH }}
          TG_SESSION_STR: ${{ secrets.TG_SESSION_STR }}
        run: python kuniaoyun.py
