name: play-monitor

on:
  schedule:
    - cron: "*/1 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - run: python main.py
        env:
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}

      - name: commit state
        run: |
          git config user.name "bot"
          git config user.email "bot@github.com"
          git add state.json
          git commit -m "update" || exit 0
          git push
